# Generated by Django 3.1.4 on 2020-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
