# Generated by Django 3.1.5 on 2021-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201211_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
