# Generated by Django 3.1.5 on 2021-06-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210604_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
