# Generated by Django 3.1.5 on 2021-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expired',
            field=models.DateTimeField(),
        ),
    ]
