# Generated by Django 3.1.5 on 2021-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210605_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expired',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
